#!/usr/bin/env bash
args=("${@:3}")

if [ -e "${args[0]}" ]; then
  dir=("${args[0]}")
  args=("${args[@]:1}")
else
  dir="$(pwd)"
fi

tmpdir="$(mktemp -d)"

cp -r "$dir"/* "$tmpdir"

args=("$tmpdir" "${args[@]}")

echo "/run/current-system/sw/bin/nixos-rebuild $1 $2 ${args[@]}"
/run/current-system/sw/bin/nixos-rebuild "$1" "$2" "${args[@]}"

rm -rf "$tmpdir"

echo "finished"
