#!/usr/bin/env bash
args=("${@:3}")

dir="${args[0]}"
[ -e "$dir" ] && args=("${args[@]:1}") || dir="$(pwd)"

tmpdir="$(mktemp -d)"

cp -r -- "$dir"/* "$tmpdir"

args=("$tmpdir" "${args[@]}")

echo "/run/current-system/sw/bin/nixos-rebuild $1 $2 ${args[@]}"
/run/current-system/sw/bin/nixos-rebuild "$1" "$2" "${args[@]}"

rm -rf "$tmpdir"

echo "finished"
